name: Esteira de Integracao do Projeto

on:
  push:
    branches:
      - main

jobs:
  integracao:
    name: Job de Integracao
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Unit Test
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest
      - name: BDD Acceptance Test
        run: |
          behave

      - name: Log in to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container Image
        run: docker build . -t felipefg/infnet-vaichover:$(date +%y%m%d).$(git rev-parse HEAD | head -c 7) -t felipefg/infnet-vaichover:latest

      - name: Push Image to DockerHub
        run: docker push -a felipefg/infnet-vaichover